"""
This is a one-off script to download ground truth (fluview) and sensors from
the delphi api. Nowcasts are generated by nowcast_experiment.py. It's best to
run this on the server since there is considerable latency when running this
remotely.

python3 -m nowcast.doc.plos.code.download_data
"""


from delphi.epidata.client.delphi_epidata import Epidata
from delphi.nowcast.util.flu_data_source import FluDataSource
from delphi.operations import secrets
from delphi.utils.geo.locations import Locations


weeks = Epidata.range(201030, 201824)


def download_fluview(f):
  for loc in Locations.region_list:
    print('fluview', loc)
    resp = Epidata.fluview(loc, weeks, auth=secrets.api.fluview)
    rows = Epidata.check(resp)
    for row in rows:
      week, value = row['epiweek'], row['wili']
      f.write('%d,%s,%.5f\n' % (week, loc, value))


def download_sensors(f):
  for sensor in FluDataSource.SENSORS:
    for loc in Locations.region_list:
      print(sensor, loc)
      resp = Epidata.sensors(secrets.api.sensors, sensor, loc, weeks)
      if resp['result'] not in (1, -2):
        raise Exception(resp['result'])
      if resp['result'] == -2:
        print('(no data)')
        continue
      for row in resp['epidata']:
        week, value = row['epiweek'], row['value']
        f.write('%d,%s,%s,%.5f\n' % (week, sensor, loc, value))


def main():
  print('downloading... this may take a while (1m1.219s to be exact)')
  with open('fluview.csv', 'w') as f:
    download_fluview(f)
  with open('sensors.csv', 'w') as f:
    download_sensors(f)


if __name__ == '__main__':
  main()
